name: Release Automation

# DÜZELTİLMİŞ "on" BLOĞU (EN KRİTİK KISIM)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Generate version tag
        id: versioning
        run: |
          VERSION=$(date +'%Y.%m.%d')
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Generated version: $VERSION"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true